### ISSUE TITLE
fix: flutter_gen breaks current template

### ISSUE THREAD

**Issue by NonymousMorlock** [VeryGoodOpenSource/very_good_cli#987] opened 2024-03-05 22:22 UTC
**Description**
After updating to very_good cli v0.20, and running create, it outputs a flutter project that depends on `flutter_gen: any`, so that when you run pub get, the `l10n.dart` errors out.

```bash
Target of URI doesn't exist: 'package:flutter_gen/gen_l10n/app_localizations.dart'.
```

**Steps To Reproduce**

1. Update your very_good_cli to v0.20
2. Create new flutter project
3. Open project in IDE
4. Run `pub get`
5. See error

**Expected Behavior**
Should compile successfully after running pub get

**Additional Context**
The template for the previous version of `very_good_cli` doesn't explicitly add `flutter_gen` to `pubspec.yaml`

**Comment by haenah** [comment] 2024-03-06 00:18
Same here ✋

**Comment by haenah** [comment] 2024-03-06 07:34
I fixed that with removing `flutter_gen` package dependency from `pubspec.yaml`.  
I think since `flutter_gen` is already in pub.dev([link](https://pub.dev/packages/flutter_gen)), and dart resolves `flutter_gen` with that package, so the generated code in `.dart-tool` is not used.

**Comment by NonymousMorlock** [comment] 2024-03-06 09:41
> I fixed that with removing `flutter_gen` package dependency from `pubspec.yaml`. I think since `flutter_gen` is already in pub.dev([link](https://pub.dev/packages/flutter_gen)), and dart resolves `flutter_gen` with that package, so the generated code in `.dart-tool` is not used.

Yeah, hopefully they fix it so we don't have to manually do that every project

**Comment by alestiago** [comment] 2024-03-06 11:00
Somewhat duplicate of #973. I haven't been able to reproduce this myself, and the [template itself](https://github.com/VeryGoodOpenSource/very_good_templates/blob/main/very_good_core/__brick__/%7B%7Bproject_name.snakeCase()%7D%7D/pubspec.yaml) doesn't seem to have `flutter_gen` explicitly defined in its `pubspec`.

@wolfenrain can you try to reproduce?

**Comment by NonymousMorlock** [comment] 2024-03-06 12:18
Then it could be from another source, maybe flutter create,  as one of the comments in the issue you referenced suggests. and from what I see in that issue, this problem has been since before 0.20, but I've personally never encountered it since I started using very_good_cli and it's been a couple years, this is my first time encountering this. so it could be a random occurrence. I tried to create a new project tho and the same happened.

**Comment by wolfenrain** [comment] 2024-03-06 14:55
> Somewhat duplicate of #973. I haven't been able to reproduce this myself, and the [template itself](https://github.com/VeryGoodOpenSource/very_good_templates/blob/main/very_good_core/__brick__/%7B%7Bproject_name.snakeCase()%7D%7D/pubspec.yaml?rgh-link-date=2024-03-06T11%3A00%3A50Z) doesn't seem to have `flutter_gen: any` explicitly defined in its `pubspec.yaml`.
> 
> @wolfenrain can you try to reproduce?

I haven't been able to reproduce this here locally either. @NonymousMorlock can you maybe provide the output of `flutter doctor`. Just to ensure that we can reproduce it in a similar environment as you have.

**Comment by NonymousMorlock** [comment] 2024-03-06 18:34
> I haven't been able to reproduce this here locally either. @NonymousMorlock can you maybe provide the output of `flutter doctor`. Just to ensure that we can reproduce it in a similar environment as you have.

```shell
[✓] Flutter (Channel stable, 3.19.0, on Fedora Linux 39 (Workstation Edition)
    6.7.7-200.fc39.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.87.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by craiglabenz** [comment] 2024-03-10 01:59
@wolfenrain I just encountered this today - happy to reproduce it together later this week if you'd like.

**Comment by NonymousMorlock** [comment] 2024-03-12 10:44
@craiglabenz I'm freaking out right now. Big fan, no no, Biggest FANNN, no way you're in my issue 😭😭😭😭😭😭

**Comment by haenah** [comment] 2024-03-15 00:35
Hi, I thihk I've found the reason.  
After I execute `dart fix`, the following fix is made:
```
pubspec.yaml
  MISSING_DEPENDENCY • 1 fix
```
This is triggered by importing `package:flutter_gen` without declaring it inside `pubspec.yaml`. So dart fixer automatically add the `flutter_gen: any` line inside it.

**Comment by gyakhoe** [comment] 2024-04-09 19:56
As of current date and time this issue still persist. Today I updated all my IDE and tools to make a new flutter app. I got the same issue. 

Strangely, If i create a project using the very_good cli in old directory, this issue didn't appear. I tried making new folder in documents and created a new project using very_good. Then there seem to be issue. 

Note: this could be false positive or something to do with directory permission. But i fix it by removing flutter_gen: any in pubspec.yaml

**Comment by oengmengthong** [comment] 2024-04-12 06:12
> As of current date and time this issue still persist. Today I updated all my IDE and tools to make a new flutter app. I got the same issue.
> 
> Strangely, If i create a project using the very_good cli in old directory, this issue didn't appear. I tried making new folder in documents and created a new project using very_good. Then there seem to be issue.
> 
> Note: this could be false positive or something to do with directory permission. But i fix it by removing flutter_gen: any in pubspec.yaml

I solved by remove flutter_gen too. because flutter_gen already building with flutter

**Closed** 2024-04-24 11:45 UTC
Labels: bug, p1
