### ISSUE TITLE
fix: No active package very_good_cli.

### ISSUE THREAD

**Issue by tsvillain** [VeryGoodOpenSource/very_good_cli#998] opened 2024-03-24 19:48 UTC
**Description**
I am trying to install/activate "very_good_cli" in my mac, using `dart pub global activate very_good_cli` but follwing error: 
```
+ _fe_analyzer_shared 67.0.0.8s)
+ analyzer 6.4.1
+ archive 3.4.10
+ args 2.4.2
+ async 2.11.0
+ boolean_selector 2.1.1
+ checked_yaml 2.0.3
+ cli_completion 0.5.0
+ cli_util 0.4.1
+ collection 1.18.0
+ convert 3.1.1
+ coverage 1.7.2
+ crypto 3.0.3
+ csslib 1.0.0
+ equatable 2.0.5
+ ffi 2.1.2
+ file 7.0.0
+ frontend_server_client 3.2.0
+ glob 2.1.2
+ html 0.15.4
+ http 1.2.1
+ http_multi_server 3.2.1
+ http_parser 4.0.2
+ io 1.0.4
+ js 0.7.1
+ json_annotation 4.8.1
+ lcov_parser 0.1.2
+ lints 3.0.0
+ logging 1.2.0
+ markdown 7.2.2
+ mason 0.1.0-dev.52
+ mason_logger 0.2.12
+ matcher 0.12.16+1
+ meta 1.12.0
+ mime 1.0.5
+ mustache_template 2.0.0
+ node_preamble 2.0.2
+ package_config 2.1.0
+ pana 0.22.1 (0.22.2 available)
+ path 1.9.0
+ platform 3.1.4
+ pointycastle 3.7.4
+ pool 1.5.1
+ process 5.0.2
+ pub_semver 2.1.4
+ pub_updater 0.4.0
+ pubspec_parse 1.2.3
+ retry 3.1.2
+ safe_url_check 1.1.2
+ shelf 1.4.1
+ shelf_packages_handler 3.0.2
+ shelf_static 1.1.2
+ shelf_web_socket 1.0.4
+ source_map_stack_trace 2.1.1
+ source_maps 0.10.12
+ source_span 1.10.0
+ stack_trace 1.11.1
+ stream_channel 2.1.2
+ string_scanner 1.2.0
+ tar 1.0.4
+ term_glyph 1.2.1
+ test 1.25.2
+ test_api 0.7.0
+ test_core 0.6.0
+ typed_data 1.3.2
+ universal_io 2.2.2
+ very_good_cli 0.20.0
+ very_good_test_runner 0.2.0
+ vm_service 14.2.0
+ watcher 1.1.0
+ web 0.5.1
+ web_socket_channel 2.4.4
+ webkit_inspection_protocol 1.2.1
+ win32 5.3.0
+ yaml 3.1.2
Could not find a file named "pubspec.yaml" in "/Users/tsvillain/.pub-cache/hosted/pub.dev/very_good_cli-0.20.0".
```

And if trying to run it using `dart pub global run very_good_cli:very_good create` which shoud be used if we this is not possible (e.g. in CI)
Output:
`No active package very_good_cli.`

**Comment by tsvillain** [comment] 2024-03-24 20:10
After cleaning dart global cache and reinstalling using using `sudo dart pub global activate very_good_cli`

When I try to create a project. It's not working please see the log below:
```
tsvillain@Tekeshwars-MacBook-Air Desktop % sudo dart pub global activate very_good_cli
Password:
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Package very_good_cli is currently active at version 0.20.0.
The package very_good_cli is already activated at newest available version.
To recompile executables, first run `dart pub global deactivate very_good_cli`.
Installed executable very_good.
Activated very_good_cli 0.20.0.
tsvillain@Tekeshwars-MacBook-Air Desktop % very_good create hello                
No active package very_good_cli.
```

**Comment by FadyFawzyOfficial** [comment] 2024-05-16 10:59
Is that bug fixed?

**Comment by tsvillain** [comment] 2024-05-16 12:07
No, it dropped the idea to use this package.

**Comment by alestiago** [comment] 2024-05-16 14:15
Hi @tsvillain! Thanks for opening an issue 💙 and sorry for the late reply. I am not able to reproduce this behaviour. Can you provide an output of your `flutter doctor`? (cc @tsvillain )

**Comment by alestiago** [comment] 2024-06-18 10:25
Hey @tsvillain  since this seems to be silent for a while, I am closing this for now. If anything comes up, don't hesitate on telling.

**Closed by alestiago** 2024-06-18 10:25 UTC
Labels: bug, waiting for response
