### ISSUE TITLE
fix: error running very_good test --coverage

### ISSUE THREAD

**Issue by jscarl** [VeryGoodOpenSource/very_good_cli#400] opened 2022-05-16 03:09 UTC
**Description**
I've fresh `very good cli` installation then there shows an error. If I pass --no-optimization args it's work. I'm attaching a file for more details.

**Steps To Reproduce**

1. dart pub global activate very_good_cli 0.7.2
2. very_good test --coverage

**Expected Behavior**
Expect the test is running.

**Screenshots**
<img width="977" alt="Screen Shot 2022-05-16 at 09 52 31" src="https://user-images.githubusercontent.com/19910954/168512353-300bdc68-bdaa-483e-b235-a6fc6f2b11b3.png">

**Additional Context**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by felangel** [comment] 2022-05-17 21:19
Hi @jscarl 👋 
Thanks for opening an issue!

Are you able to provide a link to a minimal reproduction sample? Thanks!

**Comment by mugbug** [comment] 2022-06-10 16:13
Not sure if this helps, but check this comment I added on the other issue: https://github.com/VeryGoodOpenSource/very_good_cli/issues/401#issuecomment-1152523192

**Comment by felangel** [comment] 2022-06-22 20:19
Closing for now since there aren't any actionable steps we can take. Feel free to provide additional context and I'm happy to revisit this 👍

**Closed by felangel** 2022-06-22 20:19 UTC
Labels: bug, waiting for response
