### ISSUE TITLE
fix: [very_good test]  Error: Unable to spawn isolate: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.

### ISSUE THREAD

**Issue by irvine5k** [VeryGoodOpenSource/very_good_cli#902] opened 2023-12-01 18:04 UTC
**Description**
I'm getting a non-deterministic error while running very_good test --coverage on CI

```
An exception occurred while executing hook: /home/runner/.mason-cache/bundled/test_optimizer_0.1.0+1_e75152fb8e2e89ad903bebdc62f817ee4c526819/hooks/pre_gen.dart.
Error: Unable to spawn isolate: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.
```

I couldn't find a way to reproducible, I'm using melos and that's how the CI step is configured so far:
`melos exec -c 8 --fail-fast "very_good test --coverage"`
-c configures how many packages I want to run at the same time.

Sometimes I get the error right away, sometimes just some packages throws the error.

**Comment by alestiago** [comment] 2023-12-14 13:57
Hi @irvine5k, sorry for the late reply.

Does this also happen when you are not using Melos? Have you made sure you've activated Very Good CLI using `dart pub global activate very_good_cli` within the CI or instead use `dart pub global run very_good_cli:very_good <command> <args>? 

If the above doesn't help could you specify what CI are you running this on? What `very_good_cli` version are you using? What is the output of your `flutter doctor`?

If you can't provide reproductive steps it is likely the team won't prioritise this issue.

**Comment by alestiago** [comment] 2024-01-09 15:30
Hey @irvine5k  since this seems to be silent for a while, I am closing this for now. If anything comes up, don't hesitate on telling.

**Closed by alestiago** 2024-01-09 15:30 UTC
Labels: waiting for response, investigating
