### ISSUE TITLE
Can't build for macos.  Folder not generated with create command.

### ISSUE THREAD

**Issue by Ciph3rzer0** [VeryGoodOpenSource/very_good_cli#608] opened 2022-12-17 11:46 UTC
**Description**
When I try to run a mac build, I get this error: 
```
The Xcode project defines schemes: Flutter Assemble, Runner
Exception: You must specify a --flavor option to select one of the available schemes.
```

**Steps To Reproduce**

Create a new app with very good cli.

**Expected Behavior**
macos folder created, but it's not.

**Screenshots**

**Additional Context**
As indicated here: [in this issue comment](https://github.com/VeryGoodOpenSource/very_good_cli/issues/467#issuecomment-1218533766), the macos folder is not generated even if flag is explicitly given.

I didn't really notice this at first as I'm not targeting macos, however building for mac on mac is important for testing responsiveness, and using the Device Preview tool.  I am new to macs and mac development, literally never seen xcode before, so I don't have the time or desire to figure out how to manipulate the standard flutter macos folder into working with configuration.  The handful of solutions I tried from about an hour of googling is already giving me a headache.

**Comment by felangel** [comment] 2022-12-17 16:19
Hi @Ciph3rzer0 👋
Thanks for opening an issue!

We officially don’t have MacOS support for the core template because of lack of support for MacOS flavors. See https://github.com/VeryGoodOpenSource/very_good_cli/issues/452.

I’m going to close this for now since it’s a duplicate of #452.

**Closed by felangel** 2022-12-17 16:19 UTC
Labels: duplicate
