### ISSUE TITLE
fix: Versioning error when creating a new flutter project with "very_good create"

### ISSUE THREAD

**Issue by Frankdroid7** [VeryGoodOpenSource/very_good_cli#765] opened 2023-07-27 15:22 UTC
**Description**
Tried creating a new flutter project called `predicto` with `very_good create flutter_app predicto` but I encountered a versioning issue.

**Steps To Reproduce**

1. Run `very_good create flutter_app predicto` and see the errors.

**Expected Behavior**
Expected the flutter project to be created without any version errors.

**Screenshots**
<img width="877" alt="Screenshot 2023-07-27 at 16 22 01" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/30746679/c840bc82-0994-451f-b76c-9a6c6e1611f6">

**Additional Context**
Main error: `Because predicto depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because predicto depends on intl ^0.17.0, version solving failed.`

Thanks!

**Comment by renancaraujo** [comment] 2023-09-14 15:02
Hello there!

Which version of the CLI and flutter are you using?

**Comment by Frankdroid7** [comment] 2023-09-14 15:11
very_good_cli v0.13.1 and Flutter v3.10.6

**Comment by renancaraujo** [comment] 2023-09-14 16:17
That version of `very_good_cli` includes some old templates.


 For Flutter version past 3.10.0, run `very_good update` to get the last version.
 
 
 Closing for being a duplicate of https://github.com/VeryGoodOpenSource/very_good_cli/issues/738#issuecomment-1560029856

**Closed by renancaraujo** 2023-09-14 16:17 UTC
Labels: question

**Comment by icodeyou** [comment] 2023-10-30 14:29
I had the same issue running `very_good create flutter_app test`
If you did this, just don't use `test` as a name for your app.

**Comment by Frankdroid7** [comment] 2023-10-30 20:01
The name of the app I used was `predicto`
