### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by niklasbartsch** [VeryGoodOpenSource/very_good_cli#294] opened 2022-02-21 16:15 UTC
This updating to very good cli, I have a problem to archive my iOS App. 

It can't find the modules in the "GeneratedPluginRegistrant.m" 

What am I missing?

![Bildschirmfoto 2022-02-21 um 17 15 02](https://user-images.githubusercontent.com/32355097/154992270-ef9cf184-920f-4076-97d5-a6d50bcf2c7b.png)

**Comment by marcossevilla** [comment] 2022-02-21 16:25
hey @niklasbartsch 👋 have you tried running `flutter clean` in the root of your project and then `pod install` in your ios folder?

**Comment by niklasbartsch** [comment] 2022-02-21 20:49
Didn't solve it. Still no module found...

Is there a way to say something like `flutter build ios` for the `very_good_cli`?

**Comment by niklasbartsch** [comment] 2022-02-21 20:51
What I haven't mentioned, it is working on iOS Simulator

**Comment by marcossevilla** [comment] 2022-02-22 03:09
@niklasbartsch I think I've found an answer to that issue [here](https://stackoverflow.com/questions/66685348/flutter-fatal-error-module-firebase-analytics-not-found).

> Is there a way to say something like `flutter build ios` for the `very_good_cli`?

`very_good_cli` generates an opinionated Flutter project but every Flutter command can be used with the project, like `flutter build` or `flutter clean`, so there's no need for a specific build command on the CLI.

I'm closing this issue as the default core template doesn't support Firebase by default and the issue is related to Firebase Analytics, but feel free to open an issue on the [FlutterFire](https://github.com/firebaseextended/flutterfire) repository if the link I shared above doesn't work. 👍

**Closed by marcossevilla** 2022-02-22 03:09 UTC
Labels: question, waiting for response

**Comment by niklasbartsch** [comment] 2022-02-22 11:21
But `flutter build ios` isnt't working. I am getting `Target file "lib/main.dart" not found.`

**Comment by niklasbartsch** [comment] 2022-02-22 17:27
Thank you!

I just saw, that I send the wrong Screenshot. I delete this line. This is the exact error. So maybe its the `app_tracking_transparency` package...

<img width="779" alt="Bildschirmfoto 2022-02-22 um 18 26 09" src="https://user-images.githubusercontent.com/32355097/155185574-3c25a5d1-d29c-4764-b5ed-0295ef7b5d75.png">

**Comment by niklasbartsch** [comment] 2022-02-22 21:54
I finally found the solution that works for me. 

I have to manually select a different Build Configuration for the default archive configuration.

From this: 
<img width="843" alt="Bildschirmfoto 2022-02-22 um 22 52 06" src="https://user-images.githubusercontent.com/32355097/155225882-4a117f9b-bad1-4c18-8a6d-d75974bb38a1.png">

To this: 
<img width="939" alt="Bildschirmfoto 2022-02-22 um 22 53 41" src="https://user-images.githubusercontent.com/32355097/155225917-5416f9b3-af1b-45e7-89c3-9ad09be3382d.png">
