### ISSUE TITLE
feat: fvm support

### ISSUE THREAD

**Issue by tomassasovsky** [VeryGoodOpenSource/very_good_cli#491] opened 2022-09-02 22:23 UTC
Using `fvm` I specify the flutter version to be used per-directory basis. It may mean that I don't have `flutter` available globally, or it can link to a different version of `flutter` than globally accessible. This would be the version that I'd like to use when resolving dependencies for a given project.

Some tools (like `pubviz` or bash scripts using `flutter` internally) require additional steps to make this happen, like overriding `flutter` for the scope of a program, or temporarily changing `flutter` to link to the desired version, or sometimes even modifying the script itself. Being able to pass: `very_good packages get --fluter ~/fvm/versions/beta/bin/` could be really handy.

_Originally posted by @orestesgaolin in https://github.com/VeryGoodOpenSource/very_good_cli/issues/174#issuecomment-908513565_

**Comment by mugbug** [comment] 2022-10-10 20:10
I suppose this is a duplicate of https://github.com/VeryGoodOpenSource/very_good_cli/issues/439

**Comment by felangel** [comment] 2022-10-10 20:29
Closing in favor of #439

**Closed by felangel** 2022-10-10 20:29 UTC
Labels: enhancement
