### ISSUE TITLE
fix: Android Dark Mode Splash Screen is not correct

### ISSUE THREAD

**Issue by demirdev** [VeryGoodOpenSource/very_good_cli#943] opened 2024-01-11 16:38 UTC
**Description**
Android Dark Mode Splash Screen is not correct.

**Steps To Reproduce**

1. Create a flutter app with `very_good create flutter_app android_splash_problem`
3. Run production flavor in debug mode on Android 13 device.
4. See splash screen logo color is not correct.

**Expected Behavior**
Splash screen logo color must be completely black (#000000).

**Screenshots**
### yours default color (#000000)
![295980127-17769ea3-63d3-4f0c-8bb0-d57c5d102f0b](https://github.com/VeryGoodOpenSource/very_good_cli/assets/54906407/a29a78c6-7af4-4bfb-a167-73b0d748e73e)

### after changing color to #FF0000 (red)
![screenshot](https://github.com/VeryGoodOpenSource/very_good_cli/assets/54906407/68719f52-01f2-4bea-b107-029ab1c9f5c3)

**Comment by alestiago** [comment] 2024-01-12 13:40
I wasn't able to reproduce this precisely. However, I was able to see that [Very Good Core](https://github.com/VeryGoodOpenSource/very_good_core)'s splash screen doesn't adapt to the Dark Theme.

Running on Mi A2 with Android version 10 (same result in both prod and dev flavors)

<img src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/44524995/4ed26d54-68b8-4cc4-bb0c-80a39e070068" width="400px" />

**Comment by luisredondo** [comment] 2024-01-30 15:06
Hi, @demirdev! I was not able to replicate this issue.

I followed the “Steps To Reproduce” you listed and got the same results that @alestiago commented: White background with a centered black logo. My testing device is Pixel 7a with Android 14.

Please, share more details such as what device you are running or the `very_good_cli` version. Thank you!

**Comment by alestiago** [comment] 2024-02-12 11:04
Hey @demirdev since this seems to be silent for a while, I am closing this for now. If anything comes up, don't hesitate on telling

**Closed by alestiago** 2024-02-12 11:04 UTC
Labels: bug, waiting for response
