### ISSUE TITLE
Test fails with very_good test but not in flutter test

### ISSUE THREAD

**Issue by nerder** [VeryGoodOpenSource/very_good_cli#773] opened 2023-09-02 10:36 UTC
**Description**
I'm experimenting with `very_good_cli` mainly to speed up my tests. Simply running `very_good test` on my project most of my tests are breaking, while they are not when running them using `flutter test`.

An example of an error is:

`Bad state: Cannot call when within a stub response`

on a simple test like this:

```dart
    group("on UpdateCapacity event", () {
      var newCapacity = 420;

      setUp(() {
        when(mockLessonRepository.updateLessonCapacity(
                fakeGymId, testLesson.date, testLesson.id, newCapacity))
            .thenAnswer((realInvocation) => Future.value(null));
      });

      tearDown(() {
        verify(mockLessonRepository.updateLessonCapacity(
            fakeGymId, testLesson.date, testLesson.id, newCapacity));
      });

      blocTest(
        "should call repository with newCapacity",
        build: () => EditLessonBloc(
          gymId: fakeGymId,
          lessonId: testLesson.id,
          lessonDate: testLesson.date,
          lessonRepository: mockLessonRepository,
          userRepository: mockUserRepository,
          imageRepository: mockImageRepository,
          storageRepository: mockStorageRepository,
        ),
        act: (bloc) => bloc.add(
          EditLessonEvent.updateCapacity(
            newCapacity: newCapacity,
          ),
        ),
        expect: () => [],
      );
    });
```

Why is that?

**Comment by renancaraujo** [comment] 2023-10-04 09:22
Hello @nerder, there are some cases that can cause tests to break on `very_good test` that would pass on  `flutter test`:

- Dependency in between tests
- Expects on teardown
- Vars defined outside of the usual test scaffolding (setup/setupAll).

Try to run `flutter test` with random test ordering.

**Comment by renancaraujo** [comment] 2023-10-30 18:23
Hey @nerder since this seems to be silent for a while, i am closing this for now. If anything comes up, dont hesitate on telling.

**Closed by renancaraujo** 2023-10-30 18:23 UTC
Labels: bug, waiting for response

**Comment by baptistemchl** [comment] 2024-03-15 13:42
Hello, got the same issue that @nerder . Is there a solution on it ?

**Comment by alestiago** [comment] 2024-03-15 14:18
Hi @baptistemchl thank you for following up. There might be many reasons on why tests fail with `very_good test` and not with `flutter test`. Feel free to open a new issue and provide some guidance on how we can reproduce the behaviour 🙌

**Comment by baptistemchl** [comment] 2024-03-15 14:21
Hey @alestiago , finally find a the solution to my problem. In fact i had 2 goldens generated files with the same name. :)
