### ISSUE TITLE
fix: This application's locale, pt, is not supported by all of its localization delegates.

### ISSUE THREAD

**Issue by JakeHadley** [VeryGoodOpenSource/very_good_cli#635] opened 2023-02-01 07:06 UTC
**Description**
I get this warning in the logs when I start up my application on ios, set to a different locale, namely portuguese.
`[log] Warning: This application's locale, pt, is not supported by all of its localization delegates.`
I have the app_pt.arb file populated and everything functions correctly. But it still puts out this log for some reason.

**Steps To Reproduce**

1. Create app with very_good cli 3.1.0
2. Add localization file for different language
3. Switch simulator to that language

**Expected Behavior**
No Logs

**Comment by erickzanardo** [comment] 2023-02-07 14:20
@JakeHadley can you share a reproducible example?

I have just tried it, and it seems to be working as expected.

I did the following to test:

 - Ran `very_good create flutter_app l10n_issue`
 - Added the following content to `lib/l10n/arb/app_pt.arb`
 
 ```
 {
    "@@locale": "pt",
    "counterAppBarTitle": "Contador",
    "@counterAppBarTitle": {
        "description": "Text shown in the AppBar of the Counter Page"
    }
}
```

Executed the app with `flutter run --flavor development -t lib/main_development.dart`

I was able to change between the languages and the app worked without any errors.

Thanks

**Comment by erickzanardo** [comment] 2023-02-09 14:33
Closing this since we can't reproduce. If you can put together a reproducible example, please let us know, and we can re open this.

Thanks!

**Closed by erickzanardo** 2023-02-09 14:33 UTC
Labels: bug
