### ISSUE TITLE
fix: Deprecated imperative apply of Flutter's Gradle plugins

### ISSUE THREAD

**Issue by yuruyuri16** [VeryGoodOpenSource/very_good_cli#968] opened 2024-02-23 19:56 UTC
**Description**
Since Flutter 3.16, Flutter's Gradle plugins are now applied using the Plugin DSL syntax instead of the `legacy` script syntax.

More info [here](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)

**Steps To Reproduce**

1. Create a very good flutter app
2. Run in android and some deprecation messages will pop up.

**Expected Behavior**
Run with no warnings.

**Screenshots**
<img width="1435" alt="Screenshot 2024-02-23 at 14 55 57" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/36353498/dd16a54a-2a2a-426f-9293-183f13166675">

**Comment by alestiago** [comment] 2024-02-28 11:42
I was able to reproduce this issue when running on a physical Android device running on Android 10.

```txt
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply
```

**Comment by alestiago** [comment] 2024-02-28 12:06
Closing this issue, since it is being moved to `very_good_templates`, https://github.com/VeryGoodOpenSource/very_good_templates/issues/75.

**Comment by alestiago** [comment] 2024-02-28 12:06
Closing this issue, since it is being moved to `very_good_templates`, https://github.com/VeryGoodOpenSource/very_good_templates/issues/75.

**Closed by alestiago** 2024-02-28 12:06 UTC
Labels: bug
