### ISSUE TITLE
fix: Not able to find gradlew or bat or gradle wrapper when creating project from very_good create

### ISSUE THREAD

**Issue by nikesh-madhav** [VeryGoodOpenSource/very_good_cli#407] opened 2022-05-24 16:50 UTC
issue is I am not able to run ./gradlew signingReport to get sha keys. i believe it is been added to gitignore

**Comment by felangel** [comment] 2022-06-22 20:21
Hi @nikesh-madhav 👋 
Are you still able to reproduce this on the latest version of `very_good_cli` (v0.7.8)?

**Comment by nikesh-madhav** [comment] 2022-06-23 09:47
Hi @felangel , Still the issue persists with latest version.

**Comment by chengdujin** [comment] 2022-10-22 03:16
same issue here with very_good_cli 0.8.2

**Comment by felangel** [comment] 2022-10-31 18:42
Are you all able to reproduce this using `flutter create`? Is this problem unique to `very_good create`?

**Comment by felangel** [comment] 2022-11-14 19:36
Closing for now since there are no actionable next steps. If you're still facing this issue feel free to comment with additional information and we're happy to take a closer look

**Closed by felangel** 2022-11-14 19:36 UTC
Labels: bug

**Comment by yahu1031** [comment] 2023-07-20 17:03
This is happening again in the mac.


```console
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A5286i
```

```console
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (8 days ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1
```

```console
$very_good --version
0.15.0
```
